### ISSUE TITLE
Configuration: Update Workflow Permissions

### ISSUE THREAD

**Issue by charliedebs** [charliedebs/projet-mardyck-analysis#2]
Pour permettre au workflow de fonctionner correctement, nous devons vérifier les points suivants :

1. Dans Settings > Actions > General :
   - Vérifiez que "Allow GitHub Actions to create and approve pull requests" est activé
   - Dans "Workflow permissions", sélectionnez "Read and write permissions"

2. Dans Settings > Actions > Runner :
   - Vérifiez que les GitHub-hosted runners sont autorisés

3. Ensuite, nous devrons mettre à jour le fichier workflow avec le contenu suivant (à copier dans `.github/workflows/update_content.yml`) :

```yaml
name: Update Content

on:
  issues:
    types: [opened, edited]

jobs:
  process-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Process Issue Content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Processing content update request"
          python -c "
          import os
          import json
          import sys
          
          print('Starting content update process')
          "
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update content based on issue"
          git push
```

Une fois ces modifications effectuées, nous pourrons tester le système avec une nouvelle issue.
