### ISSUE TITLE
Configuration : Mise à jour du workflow pour la création de fichiers

### ISSUE THREAD

**Issue by charliedebs** [charliedebs/projet-mardyck-analysis#6]
Il semble que le workflow ait besoin d'une mise à jour pour pouvoir créer des fichiers. Voici le nouveau contenu à mettre dans `.github/workflows/update_content.yml` :

```yaml
name: Update Content

on:
  issues:
    types: [opened, edited]

jobs:
  process-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Process Issue and Create Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configuration Git
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action Bot"
          
          # Extraire le contenu de l'issue
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          
          # Créer les fichiers selon le contenu de l'issue
          echo "Processing issue: $ISSUE_TITLE"
          echo "Content: $ISSUE_BODY"
          
          # Commit et push si des changements sont détectés
          git add .
          git diff --staged --quiet || (git commit -m "Update from issue: $ISSUE_TITLE" && git push)
```

Une fois ce fichier mis à jour, le workflow devrait pouvoir créer et modifier des fichiers automatiquement.
